# .github/workflows/dns-update.yml
name: DNS Update

on:
  schedule:
    - cron: '0 */3 * * *'  # 每3小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-dns:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fix aliyunsdkcore six.py  # 添加这个步骤
        run: |
          SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
          CORE_PATH="$SITE_PACKAGES/aliyunsdkcore"
          
          mkdir -p "$CORE_PATH/vendored/requests/packages/urllib3/packages"
          curl -o six.py https://raw.githubusercontent.com/benjaminp/six/1.16.0/six.py
          
          cp six.py "$CORE_PATH/vendored/six.py"
          cp six.py "$CORE_PATH/vendored/requests/packages/urllib3/packages/six.py"
          
      - name: Update settings.json
        env:
          ALIYUN_KEY: ${{ secrets.ALIYUN_KEY }}
          ALIYUN_SECRET: ${{ secrets.ALIYUN_SECRET }}
          DNSPOD_ID: ${{ secrets.DNSPOD_ID }}
          DNSPOD_KEY: ${{ secrets.DNSPOD_KEY }}
          HUAWEI_AK: ${{ secrets.HUAWEI_AK }}
          HUAWEI_SK: ${{ secrets.HUAWEI_SK }}
          DOMAIN: ${{ secrets.DOMAIN }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        run: |
          python .github/scripts/update_settings.py
          
      - name: Run DNS update
        run: |
          python main.py
          
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            results/*.json
            logs/*.log
